---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lafolieboulart/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp reservation.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
